### ISSUE TITLE
Drag and drop does not work on Firefox Quantum

### ISSUE THREAD

**Issue by kmackinnon** [PredixDev/px-file-upload#23]
## Expected behavior and actual behavior:
Dropping a file should trigger the `px-file-upload-files-changed` event; however, this does not occur.

## Steps to reproduce the problem:
Drag and drop files (as opposed to using the upload button)

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
Firefox >= 57.0

**Comment by Ledivin** [comment]
I don't have time to go through the entire PR right now, but for the sake of not losing it, I'll document my fix here:

At the end of this.ondrop (defined in ready):

          // Firefox does not properly fire a change event when manually setting files on input.
          // Manually hitting change handler.  Duplicate calls (i.e. this one and the change event)
          // in Chrome are filtered out by debounce.
          this._fileChange({target: this.$.fileInput});

This causes a duplicate call to _fileChange in not-Firefox, because the change event still triggers as expected.  To fix the duplicate call, I wrapped the _fileChange contents in a very short (1ms) debounce.

The alternative to calling _fileChange in ondrop would be to check the navigation.userAgent string, but I know that's generally frowned upon.

**Comment by evanjd** [comment]
Resolved on v1.3.1 thanks to @Ledivin's PR.
